version: "3"

services:

  nginx:
    restart : always
    image: nginx:latest
    container_name: "nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf/
      - ./nginx/index.html:/var/www/html/index.html/
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/
    networks:
      - test

  certbot:
    image: certbot/certbot:latest
    container_name: "certbot"
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - test

networks:
  test:
    driver: bridge
